/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int lock_acquire(char *);
int lock_release(int);

int lock_acquire(char * path __attribute__((unused))) {
    return (eventstore_seqlock_acquire(path));
}

int lock_release(int fd __attribute__((unused))) {
    return (eventstore_seqlock_release(fd));
}

